services:
  db:
    image: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: dontnote
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      backend:
        ipv4_address: 172.20.0.1

  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/dontnote/src
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/dontnote?builder=public'
    networks:
      backend:
        ipv4_address: 172.20.0.2

networks:
  backend:
    ipam:
      config:
        - subnet: 172.20.0.0/16
