services:
  db:
    image: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: dontnote
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/dontnote/src
      - ./generated:/usr/src/dontnote/generated
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/dontnote?builder=public'
