version: "3"
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/dontnote/src
